# Generated by Django 4.2.7 on 2025-11-16 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('congestion', 'تراکم غیرعادی'), ('loitering', 'توقف طولانی'), ('wrong_direction', 'حرکت مخالف'), ('crowd_gathering', 'تجمع ناگهانی'), ('no_movement', 'عدم حرکت')], max_length=20, verbose_name='نوع ناهنجاری')),
                ('track_id', models.IntegerField(blank=True, null=True, verbose_name='شناسه ردیابی')),
                ('confidence', models.FloatField(verbose_name='میزان اطمینان')),
                ('frame_data', models.JSONField(verbose_name='داده\u200cهای فریم')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='رفع شده')),
            ],
            options={
                'verbose_name': 'رویداد غیرعادی',
                'verbose_name_plural': 'رویدادهای غیرعادی',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دوربین')),
                ('location_name', models.CharField(blank=True, max_length=255, verbose_name='نام موقعیت')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی')),
                ('stream_url', models.URLField(verbose_name='آدرس استریم')),
                ('camera_type', models.CharField(choices=[('entrance', 'ورودی'), ('exit', 'خروجی'), ('general', 'عمومی')], default='general', max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('calibration_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای کالیبراسیون')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دوربین',
                'verbose_name_plural': 'دوربین\u200cها',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='کلید')),
                ('value', models.JSONField(verbose_name='مقدار')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات سیستم',
                'verbose_name_plural': 'تنظیمات سیستم',
            },
        ),
        migrations.CreateModel(
            name='PeopleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_in', models.IntegerField(default=0, verbose_name='تعداد ورود')),
                ('count_out', models.IntegerField(default=0, verbose_name='تعداد خروج')),
                ('total_inside', models.IntegerField(default=0, verbose_name='مجموع حاضر')),
                ('density_map', models.JSONField(blank=True, null=True, verbose_name='نقشه تراکم')),
                ('frame_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای فریم')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.camera', verbose_name='دوربین')),
            ],
            options={
                'verbose_name': 'شمارش افراد',
                'verbose_name_plural': 'شمارش افراد',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['is_active', 'camera_type'], name='dashboard_c_is_acti_a0b00f_idx'),
        ),
        migrations.AddField(
            model_name='anomalyevent',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.camera', verbose_name='دوربین'),
        ),
        migrations.AddIndex(
            model_name='peoplecount',
            index=models.Index(fields=['timestamp', 'camera'], name='dashboard_p_timesta_5b864e_idx'),
        ),
        migrations.AddIndex(
            model_name='peoplecount',
            index=models.Index(fields=['camera', 'timestamp'], name='dashboard_p_camera__f565ca_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyevent',
            index=models.Index(fields=['timestamp', 'anomaly_type'], name='dashboard_a_timesta_832e68_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyevent',
            index=models.Index(fields=['is_resolved', 'camera'], name='dashboard_a_is_reso_846838_idx'),
        ),
    ]
