# Generated by Django 4.2.7 on 2025-11-18 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraAdvanced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_config', models.JSONField(default=dict, verbose_name='تنظیمات پردازش')),
                ('analytics_settings', models.JSONField(default=dict, verbose_name='تنظیمات آنالیتیکس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.camera', verbose_name='دوربین پایه')),
            ],
            options={
                'verbose_name': 'دوربین پیشرفته',
                'verbose_name_plural': 'دوربین\u200cهای پیشرفته',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('snapshot_data', models.JSONField(default=dict, verbose_name='داده\u200cهای آنالیتیکس')),
                ('camera_adv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='dashboard.cameraadvanced', verbose_name='دوربین پیشرفته')),
            ],
            options={
                'verbose_name': 'آنالیتیکس Snapshot',
                'verbose_name_plural': 'آنالیتیکس Snapshotها',
                'ordering': ['-timestamp'],
            },
        ),
    ]
